# Basic
title: kelvin-luo
subtitle: 个人站
description: 研究方向为计算机视觉、机器学习、深度学习、人工智能等。
# 头像里面的标题
avatarTitle: kelvin-luo
# 头像里面的描述
avatarDesc: 计算机视觉、机器学习、深度学习、人工智能等。
url: "http://kelvin-luo.github.io"

# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    github: kelvin-luo
    weibo: 5972152709
    gitee: feiyang20180101
    csdn: leoking01
    cnblogs: leoking01
    zhihu: leoking01
    bilibili: 91373110
    douyin: 0N6-7bwJ8lg
    jianshu: fba0fd3862a2
    mail: leoking03@hotmail.com
    juejin: 3444116073512686
    twitter: null
    medium: @leoking20180101
    ifdian: 620756de58b611f1a22752540025c377
    patreon: kelvinluo

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 0e731faee82e4fd0b60e58f7700c08cc

# Google Analytics
# 使用博客模板请去掉或者更换 id
# ga:
#     id: UA-84134159-3  
#     host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 技术支持, description: support, url: '/support'}      
    - {title: 关于我, description: about, url: '/about'}   
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


